name: Simple APK Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      
    - name: Make gradlew executable
      run: chmod +x CloudCounter/gradlew
      
    - name: Clean and Build APK
      run: |
        cd CloudCounter
        ./gradlew clean
        if [ "${{ github.event.inputs.build_type }}" == "debug" ]; then
          ./gradlew assembleDebug
        else
          ./gradlew assembleRelease
        fi
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-${{ github.event.inputs.build_type }}-${{ github.run_number }}
        path: CloudCounter/app/build/outputs/apk/**/*.apk
        retention-days: 7